agent_id: AV_Virtual_1

topics:
  - name: /vehicle/status/gear_status
    type: autoware_vehicle_msgs.msg.GearReport
    serializer: gear_report_to_json
    mqtt_topic: pingpong/{agent_id}/gear_report 

  - name: /vehicle/status/velocity_status
    type: autoware_vehicle_msgs.msg.VelocityReport
    serializer: velocity_report_to_json
    mqtt_topic: pingpong/{agent_id}/velocity_report

  - name: /vehicle/status/actuation_status
    type: tier4_vehicle_msgs.msg.ActuationStatusStamped
    serializer: actuation_report_to_json
    mqtt_topic: pingpong/{agent_id}/actuation_report
  
  - name: /vehicle/status/steering_status
    type: autoware_vehicle_msgs.msg.SteeringReport
    serializer: steering_report_to_json
    mqtt_topic: pingpong/{agent_id}/steering_report
  
  - name: /vehicle/status/control_mode
    type: autoware_vehicle_msgs.msg.ControlModeReport
    serializer: control_mode_report_to_json
    mqtt_topic: pingpong/{agent_id}/control_mode_report
  
  - name: /vehicle/status/hazard_lights_status
    type: autoware_vehicle_msgs.msg.HazardLightsReport
    serializer: hazard_lights_report_to_json
    mqtt_topic: pingpong/{agent_id}/hazard_lights_report

  - name: /vehicle/status/turn_indicators_status
    type: autoware_vehicle_msgs.msg.TurnIndicatorsReport
    serializer: turn_indicators_report_to_json
    mqtt_topic: pingpong/{agent_id}/turn_indicators_report

  - name: /localization/kinematic_state
    type: nav_msgs.msg.Odometry
    serializer: kinematic_report_to_json
    mqtt_topic: pingpong/{agent_id}/kinematic_state

  - name: /perception/traffic_light_recognition/external/traffic_signals
    type: autoware_perception_msgs.msg.TrafficLightGroupArray
    serializer: traffic_light_group_array_to_json
    mqtt_topic: pingpong/{agent_id}/external/traffic_light_groups

  - name: /perception/object_recognition/tracking/objects
    type: autoware_perception_msgs.msg.TrackedObjects
    serializer: tracked_objects_to_json
    mqtt_topic: pingpong/{agent_id}/tracked_objects

static_announcement:
  mqtt_topic: pingpong/AV_Virtual_1/static_announcement
  payload:
    agent_id: "AV_Virtual_1"
    make: "Lexus"
    model: "Some_model"
    publications: ["pingpong/AV_Virtual_1/gear_report",
      "pingpong/{agent_id}/velocity_report",
      "pingpong/AV_Virtual_1/actuation_report",
      "pingpong/AV_Virtual_1/steering_report",
      "pingpong/AV_Virtual_1/control_mode_report",
      "pingpong/AV_Virtual_1/hazard_lights_report",
      "pingpong/AV_Virtual_1/turn_indicators_report",
      "pingpong/AV_Virtual_1/kinematic_state",
      "pingpong/AV_Virtual_1/tracked_objects"
      #"pingpong/AV_Virtual_1/external/traffic_light_groups"

    ]