sensor_kit_base_link:
  os1_top_base_link: # Lidar
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  navsat_link: # INS-GNSS
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0
  traffic_light_left_camera/camera_link: # Camera
    x: 1.1428
    y: -0.1726
    z: -0.5088
    roll: 1.5834
    pitch: -0.0011
    yaw: -1.5764

